### ISSUE TITLE
configurable sidebar

### ISSUE THREAD

**Issue by zermelozf** [linalgo/client#19]
The behaviour of the sidebar in local mode, hosted mode and browser mode is slightly different. These behaviour should be configurable in one way or another using simple configuration flags/options.

**Injection location**
- [ ] Locally and in browser mode, the sidebar should be injected inside the root element of the page
- [x] Hosted inside `linalgo/annotate-web` it should be injected inside the appropriate `<div>` element

**Task or annotator**
- [x] Locally and in browser mode, the top drop-down menu should allow selection of the appropriate task
- [ ] Hosted inside `linalgo/annotate-web`, the top drop-down menu should allow selection of different annotators. When an annotator is selected, only the annotations made by this person are shown.
